### ISSUE TITLE
Feat.req. Win binary

### ISSUE THREAD

**Issue by necros2k7** [ern0/shrinkshot#1]
subj

**Comment by ern0** [comment]
I am not familiar with Windows, but I have a machine with Windows10, so, I will look after whether PowerShell has use-program-output-as-args (e.g. _gcc \`cat gccopts\`_ - with backward aposthrophe) functionality. If yes, I need just complete the manual (how to install imagemagick for Windows, PowerShell command etc.). If not, instead of displaying args, my program should go master and launch imagemagick with args calculated.

Stay tuned!

**Comment by ern0** [comment]
New CLI interface:
` shrinkshot screenshot.png result.png
`
I've added a Windows exe, but not tested yet (I have no Windows at home), it crashes Wine (Wine has no Imagemagick installed). I'll add some words on how to install Imagemagick.

Probably it will work, if you install Imagemagick properly. You can check it by entering "convert" at command prompt. Don't forget to add Imagemagick's directory to the system path.

Check _develop_  branch. After testing, I'll merge the fixed stuff to _master_.

**Comment by necros2k7** [comment]
tried on win10:
C:\TST>shrinkshot 1.png 2.png
shrinkshot: error processing file 1.png
(imagemagick files in same dir)
![1](https://user-images.githubusercontent.com/16452453/68826060-61e92680-06ad-11ea-9bb4-e609c60127e5.png)

**Comment by ern0** [comment]
Added Windows executable, see `bin/` directory. I hope, it works, tested on Win10.

Found a bug, which occurred error only on Windows systems: `upng_free()` was called right after loading the image, converter was working on memory area which was already released by `upng_free()`. (On Linux, if you `free()` some memory, it will remain in the process' VM area for a while, so it may be no segfault, if you use it.)

**Comment by necros2k7** [comment]
I tried and it ran with a bug I posted above

**Comment by ern0** [comment]
If you have spaces in any filename, download the new one. What do you mean "bug"? Is the result not satisfactory? You should attach example source image.

**Comment by necros2k7** [comment]
https://github.com/ern0/shrinkshot/issues/1#issuecomment-553715808

I posted my problem above, I will repeat:
"tried on win10:
C:\TST>shrinkshot 1.png 2.png
shrinkshot: error processing file 1.png
(imagemagick files in same dir)"

**Comment by ern0** [comment]
You may try to convert one of the files from `test/` directory.

If you can attach `1.png`, I can try it.

**Comment by necros2k7** [comment]
I already embedded it above under my message (black screenshot) , just save it as image and try to use on your utility
https://user-images.githubusercontent.com/16452453/68826060-61e92680-06ad-11ea-9bb4-e609c60127e5.png

**Comment by ern0** [comment]
UPNG (the PNG library I'm using) does not support this image, I've added displaying UPNG errors:
`shrinkshot: error processing file black_bug.png, upng error 7 (image color format is not supported)`
